### ISSUE TITLE
alphafold2 error : Cannot create a tensor proto whose content is larger than 2GB.

### ISSUE THREAD

**Issue by HimansuKumarIIITA** [kalininalab/d-StructMAn#4]
When I was running alphafold2 for protein structure prediction, it was running perfectly fine for smaller number of amino acids. In case of larger amino acids protein such as 700 long AA, its throwing error : 
 
Command:

python3 docker/run_docker.py --fasta_paths=docker/BCR_ABL.fasta --max_template_date=2020-05-14

Error:
I1030 14:11:24.108233 140521650726720 run_docker.py:195] "Cannot create a tensor proto whose content is larger than 2GB.")
I1030 14:11:24.108459 140521650726720 run_docker.py:195] ValueError: Cannot create a tensor proto whose content is larger than 2GB.

Please guide to resolve this issue.

**Comment by sanjaysrikakulam** [comment]
Hi @HimansuKumarIIITA 

I am sorry this repository has nothing to do with Alphafold. Please create a ticket in the correct repo https://github.com/deepmind/alphafold

Also, we have a non-docker version of Alphafold which can be found here: https://github.com/kalininalab/alphafold_non_docker
